language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

services:
    - docker
    - rabbitmq
    - redis

env:
    global:
        - TEST_COMMAND="composer test-ci"
        - secure: "nk2Nm/xFmdp/sakc1q0/rEH/yUVvEzMSbh1trRMp6ldHCzscBTYFnVFrnwf8G6qpaYR604sQV3yujEE1r9B8DZ4mDsHD8WbOtUyaNLINeUnL2uEHXyukE76Bf3hjkSLvKdpriQDZA5xvbfXUBYoh81CdmT9OaQnUtblMe5BN93xB7VsNB68+eCiPK0IUFKTby59rm6ewVB4kanljtvwOunuEfZXvqdfg7HtArN1tWxd8Bn58KaLvYlndFXtLsTlhygnmJAbKd4Mk6H+OVd5Z3Qq3UXaKFBh7ovrob/aWHBLFLGhr6Ga1palh7d2sdO4wCn8dVfbTlvVRvcqxQmwBHUoGOr1/918caN3ZWjEF21kmX8BgK+lHOvexrAPo15jOL6ZXYhJY4zAAZmMXHUAYHxM0UUNPd3KywhdFan3PNsVCYgldcpsU6unnP9PKv/upm+holWnUvd7fgUrZtcnD2Q8lAihkxF7HJrFttqnm0qaipbOFp9flwxskkQbE0qAZZm16GuCw0Yfky3h9YyQ7nIOjWlF9t8/Z4d1VxrwTcNc8Zba4vM5OdvB9qVRrc0ZJVj2z/PeEPJOO0ytUBO/Y+hz10iReGLHtZZukR6RDaF0XlGVwynBPIS6Hu54t3S30jg/DYu8e0jwlb2rP/+LpFpv+ALUzl95a3SWhqgVsjCc="
        - secure: "kQj2YVCU3Hc4R7CVGKfWl3jieP1vEjAkxbUyUCpNC37IYrXujajKdyXbcWBXUeDa++HfICdlBikPdfh/mPC+/WozaBNzoOIFTOEN5zmE9WPLtnB1d7QB5zTnQBX9rb59il+bYfgm8IL2iwK3mupryP8Kspt4nMjVjsEz4sxtqe/XR23RuEgf4UFPqZEZdKSjnwGiUuERvRderkcpROAu7/6X79OFnbjZLDgT/j+eCQypvYXievn700DnWCwRaCBcqB3DepkrppfiXmZLRAjKUgMRVCi0ILfpoUF7rK3aS8hLC0YlIYjmc62HT+KP16NP9htXxZ+DNCH5OEmZjR8pRli3is1RFqeviM+v/Mx4mEpYkTNcoJygE8blFareudQu6ofwrAT/W6q/7LFtjVA2F6wc8CLztZawaqTBxdIhRdZj5q8FTt7lfJaVPsk5/dimz75iinH1opOJPkpBU2rbg3erPWxBz4tvlq3cEfvS/P7y/OFQ1eCEDl2Wi8Y+kSYcEpDDplAg6WGS2KEMx40bVPSZgZ0H0omnchnwuZuJBoSgoSjcSRvUv21ljttCyCVQJfxHpxoLNk6N5BOsTIi5AXu0grIvGiyoNuO9zqLKzuxdYTMqPmLAqLJL0k/R0HzRyL8q2H3UecEaC0etFOvCV/DT5kQLZSjyVSMRfAJ1sL8="
        - secure: "QM3I9ZP1U1eo32iIb/I8x4J4sYlx1W0U7dhvA+2vPoU67JWg/CkBTDBZmNTZl7qP+/TRXO+QlKoClkwBX/CsthEYuuqN35cxs3tVEEMBsnoK3oLxgWG6RmyrHmHd5Jv5JIJucuugcfq3bevVRlqRUJM+uPvO9PvbwPyXxYsMudroXZRhS9a7ZXtkdDh1A2rWJBgakuXHy+rlq8nUnEf3yiKFLxVe9SJdzVVXYeEVthiTe65R8R5AAXMR/UQtdO3CD1/g5Jk2kNXDJKDTUjuRqBo1s2ACX22Eg1eGK//KDR9agMAj8L4thTlJoZMz0q8vqP7FezUvPSN+5GAL8LUy5ODAqO37fqtSmoXWSbcHndNtCnHVTucOe1l0NLLHlTozW//iaK8JknaTwj4gUe9utKsVDaRwAIrkhX6TG0qZtSm375O4sGbgTMRHYNpsZQWkyojC7uAgpBk6RSgz9zvR0db+oDxZTbI/BGR7qkJB6eYiV0Gg8q4NM86D33HGO8XRB7sUjwmJouK+zZVOu4dimwQmuXbFWdXKlJDn3klxBZnPZDK4PIYCWJLZjYDwv6C987H8MMu9oU6ehzaq8RDYwyIoPJmMunc3xqXis8puR66aU2toGC0OeezK2DUI0PFyGktcdLKZQPpUX8tJ5DtOCvMq6pRtQ9Ga5+5298kxDeA="

branches:
    except:
        - /^analysis-.*$/
        - /^flintci-.*$/

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci-coverage"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

before_script:
    - cp docker-compose.override.yml.ci docker-compose.override.yml
    - docker-compose up -d
    - timeout 15 bash -c 'until echo > /dev/tcp/localhost/11300; do sleep 0.5; done'

script: $TEST_COMMAND

after_success: >
    if [[ $COVERAGE = true ]]; then
        wget https://scrutinizer-ci.com/ocular.phar

        php ocular.phar code-coverage:upload --format=php-clover build/unit_coverage.xml
        php ocular.phar code-coverage:upload --format=php-clover build/integration_coverage.xml
    fi
